#!/usr/bin/python

from google.oauth2 import service_account
import os
import sys

for entry in os.listdir('.'):
    if entry[-5:] == ".json":
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = entry


def synthesize_text(text):
    """Synthesizes speech from the input string of text."""
    from google.cloud import texttospeech
    client = texttospeech.TextToSpeechClient()

    input_text = texttospeech.types.SynthesisInput(text=text)

    # Note: the voice can also be specified by name.
    # Names of voices can be retrieved with client.list_voices().
#     voice = texttospeech.types.VoiceSelectionParams(
#         language_code='en-US',
#         ssml_gender=texttospeech.enums.SsmlVoiceGender.FEMALE)

    voice = texttospeech.types.VoiceSelectionParams(name="en-US-Wavenet-C",
        language_code='en-US',)

    audio_config = texttospeech.types.AudioConfig(
        audio_encoding=texttospeech.enums.AudioEncoding.MP3)

    response = client.synthesize_speech(input_text, voice, audio_config)

    return response.audio_content

#     # The response's audio_content is binary.
#     with open('output.mp3', 'wb') as out:
#         out.write(response.audio_content)
#         print('Audio content written to file "output.mp3"')


mp3data = synthesize_text("This is a test")

with open("output.mp3", "wb") as fp:
    fp.write(mp3data)


